/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class ViewTeam extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    
    /**
     * Creates new form ViewTeam
     */
    public ViewTeam() {
        initComponents();
        DoConnect();
    }
    
    public void DoConnect( ) {
        try {
   
            String host = "jdbc:derby://localhost:1527/JFLDB";
            String uName = "JFLAdmin";
            String uPass= "JFLAdmin";
            
            Connection connection = DriverManager.getConnection(host, uName, uPass);
            
            Statement smtEditable = connection.createStatement( ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            Statement smtUneditable = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            
            
            //query to show all records in specific result set.
            String showAllPlayerRecords = "SELECT * FROM PLAYERS Where TeamID is = '1'";
//            String showAllTeams = "SELECT * FROM TEAMS";
//            String showAllMatchesPlayed = "SELECT * FROM MATCHES";
//            String showAllReferees = "SELECT * FROM REFEREE";
//            String showLeagueTable = "SELECT * FROM LEAGUETABLE";
            
            //store 'view all records' queries in result sets
            ResultSet teamPlayersRS = smtUneditable.executeQuery(showAllPlayerRecords);
//            ResultSet allTeamsRS = smtUneditable.executeQuery(showAllTeams);
            
            while(rs.next()){
                int playerID_col = rs.getInt("PLAYERID");
                String PlayerID = Integer.toString(playerID_col);
                
                String PlayerName = rs.getString("PLAYERNAME");
                
                int playerAge_col = rs.getInt("AGE");
                String PlayerAge = Integer.toString(playerAge_col);
                
                int playerTeam_col = rs.getInt("TEAMID");
                String playerTeam = Integer.toString(playerTeam_col);
                
                String Captain = rs.getString("CAPTAIN");
                String Position = rs.getString("POSITION");
            }
        }
        catch ( SQLException err ) {
            System.out.println( err.getMessage( ) );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFLDBPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("JFLDBPU").createEntityManager();
        teamsQuery = java.beans.Beans.isDesignTime() ? null : JFLDBPUEntityManager.createQuery("SELECT t FROM Teams t");
        teamsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teamsQuery.getResultList();
        coachesQuery = java.beans.Beans.isDesignTime() ? null : JFLDBPUEntityManager.createQuery("SELECT c FROM Coaches c");
        coachesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coachesQuery.getResultList();
        coachesQuery1 = java.beans.Beans.isDesignTime() ? null : JFLDBPUEntityManager.createQuery("SELECT c FROM Coaches c");
        coachesList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coachesQuery1.getResultList();
        teamnamebutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textTeamName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        teamnamebutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teamnamebutton.setText("Search");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Enter Team Name:");

        textTeamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeamNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Miriam", 1, 36)); // NOI18N
        jLabel2.setText("Team Viewer");

        teamnamebutton1.setText("Print Record Sheet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teamnamebutton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teamnamebutton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamnamebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teamnamebutton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTeamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeamNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTeamNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 

    // Closes the Connection

 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager JFLDBPUEntityManager;
    private java.util.List<GUI.Coaches> coachesList;
    private java.util.List<GUI.Coaches> coachesList1;
    private javax.persistence.Query coachesQuery;
    private javax.persistence.Query coachesQuery1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton teamnamebutton;
    private javax.swing.JButton teamnamebutton1;
    private java.util.List<GUI.Teams> teamsList;
    private javax.persistence.Query teamsQuery;
    private javax.swing.JTextField textTeamName;
    // End of variables declaration//GEN-END:variables
}
