/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.List;
import javax.persistence.Query;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Paul
 */
public class ViewTeam extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
     
    int userEnteredID;
     
    
    /**
     * Creates new form ViewTeam
     */
    public ViewTeam() {
        initComponents();
        DoConnect();
    }
    
    public void DoConnect( ) {
        try {
            DBConnect db = new DBConnect();
            rs = db.connect("SELECT * FROM PLAYERS");
            
            /*String host = "jdbc:derby://localhost:1527/JFLDB";
            String uName = "JFLAdmin";
            String uPass= "JFLAdmin";
            
            Connection connection = DriverManager.getConnection(host, uName, uPass);
            
            //Statement smtEditable = connection.createStatement( ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            Statement smt = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            
            //query to show all records in specific result set.
            String showAllPlayerRecords = "SELECT * FROM PLAYERS";
//            String showAllTeams = "SELECT * FROM TEAMS";
//            String showAllMatchesPlayed = "SELECT * FROM MATCHES";
//            String showAllReferees = "SELECT * FROM REFEREE";
//            String showLeagueTable = "SELECT * FROM LEAGUETABLE";
            
            //store 'view all records' queries in result sets
            rs = smt.executeQuery(showAllPlayerRecords);
//            ResultSet allTeamsRS = smt.executeQuery(showAllTeams);
            */
            while(rs.next()){
                int playerID_col = rs.getInt("PLAYERID");
                String PlayerID = Integer.toString(playerID_col);
                
                String PlayerName = rs.getString("PLAYERNAME");
                
                int playerAge_col = rs.getInt("AGE");
                String PlayerAge = Integer.toString(playerAge_col);
                
                int playerTeam_col = rs.getInt("TEAMID");
                String playerTeam = Integer.toString(playerTeam_col);
                
                String Captain = rs.getString("CAPTAIN");
                String Position = rs.getString("POSITION");
                
            }
        }
        catch ( SQLException err ) {
            System.out.println( err.getMessage( ) );
        }
    }
    
//    public void FillTable(JTable table, String Query)
//    {
//        try
//        {
//            
//            Statement smt = con.createStatement();
//            ResultSet rs = smt.executeQuery(Query);
//
//            //To remove previously added rows
//            while(jTable1.getRowCount() > 0) 
//            {
//                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
//            }
//            
//            int columns = rs.getMetaData().getColumnCount();
//            
//            while(rs.next())
//            {  
//                Object[] row = new Object[columns];
//                for (int i = 1; i <= columns; i++)
//                {  
//                    row[i - 1] = rs.getObject(i);
//                }
//                ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow()-1,row);
//            }
//
//            rs.close();
//            smt.close();
//            con.close();
//        }
//        catch(SQLException e)
//        {
//        }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFLDBPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("JFLDBPU").createEntityManager();
        teamnamebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textTeamName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        teamnamebutton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TeamTable = new javax.swing.JTable();
        BackHomeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teamnamebutton.setText("Search");
        teamnamebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamnamebuttonMouseClicked(evt);
            }
        });
        teamnamebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamnamebuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Team ID:");

        textTeamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeamNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Miriam", 1, 36)); // NOI18N
        jLabel2.setText("Team Viewer");

        teamnamebutton1.setText("Print Record Sheet");

        TeamTable.setAutoCreateRowSorter(true);
        jScrollPane2.setViewportView(TeamTable);

        BackHomeButton.setText("Back to Team Manager");
        BackHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackHomeButtonMouseClicked(evt);
            }
        });
        BackHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Tip: Sort by clicking column names for descending and descending order.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackHomeButton)
                        .addGap(18, 18, 18)
                        .addComponent(teamnamebutton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamnamebutton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamnamebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(teamnamebutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BackHomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTeamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeamNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTeamNameActionPerformed

    private void teamnamebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamnamebuttonActionPerformed
//        // TODO add your handling code here:
        //userEnteredID = Integer.parseInt(textTeamName.getText());
        try{
        //rs.close();
        DBConnect dbc = new DBConnect();
        ResultSet llama = dbc.connect("SELECT * FROM PLAYERS WHERE TEAMID = " + textTeamName.getText());
        
        //DefaultTableModel model = (DefaultTableModel) TeamTable.getModel();
        
        //TeamTable.selectAll();
        //TeamTable.clearSelection();
        //playersList.clear();
        Query thing = java.beans.Beans.isDesignTime() ? null : JFLDBPUEntityManager.createQuery("SELECT * FROM PLAYERS * WHERE *.TEAMID = " + textTeamName.getText());
        List whatever = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : thing.getResultList();
//        while(true){
//        //model.addRow(new Object[]{llama.getString("POSITION"), llama.getBoolean("CAPTAIN"), Integer.toString(llama.getInt("TEAMID")),Integer.toString(llama.getInt("AGE")),llama.getString("PLAYERNAME"),Integer.toString(llama.getInt("PLAYERID"))});
//       // playellamaQuery.equals(new Object[]{llama.getString("POSITION"), llama.getBoolean("CAPTAIN"), Integer.toString(llama.getInt("TEAMID")),Integer.toString(llama.getInt("AGE")),llama.getString("PLAYERNAME"),Integer.toString(llama.getInt("PLAYERID"))});
//        //playersList.add(0, llama.getString("POSITION"));
//        
//        playersList.contains(thing.equals(new Object[]{llama.getString("POSITION"), llama.getBoolean("CAPTAIN"), Integer.toString(llama.getInt("TEAMID")),Integer.toString(llama.getInt("AGE")),llama.getString("PLAYERNAME"),Integer.toString(llama.getInt("PLAYERID"))}));
//        llama.next();
//        }
        
        }//catch (SQLException err){
          //  JOptionPane.showMessageDialog(null, err);
        //}
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        //String searchEnteredID = "WHERE TEAMID = " + textTeamName.getText();
        //playersQuery = java.beans.Beans.isDesignTime() ? null : JFLDBPUEntityManager.createQuery("SELECT * FROM TEAMS " + searchEnteredID);
        
//        playersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : playersQuery.getResultList();
    }//GEN-LAST:event_teamnamebuttonActionPerformed

    private void BackHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackHomeButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TeamManagerScreen().setVisible(true);
    }//GEN-LAST:event_BackHomeButtonMouseClicked

    private void BackHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TeamManagerScreen().setVisible(true);
    }//GEN-LAST:event_BackHomeButtonActionPerformed

    private void teamnamebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamnamebuttonMouseClicked
        // TODO add your handling code here:
                


//        String search = textTeamName.getText();
//        ViewTeam.FillTable(jTable1, "SELECT * FROM PLAYERS WHERE TEAMID == '1'");
    }//GEN-LAST:event_teamnamebuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 

    // Closes the Connection

 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackHomeButton;
    private javax.persistence.EntityManager JFLDBPUEntityManager;
    private javax.swing.JTable TeamTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton teamnamebutton;
    private javax.swing.JButton teamnamebutton1;
    private javax.swing.JTextField textTeamName;
    // End of variables declaration//GEN-END:variables
}
